Add Rod to the automation lib list.
ChromeDevTools/awesome-chrome-devtools pull request #112
Opened 2020-07-27 18:44 UTC by ysmood

Use ABC order to insert the new item.

2020-07-27 18:46 UTC, ysmood commented
@googlebot I signed it!

2020-07-28 17:27 UTC, ysmood commented
Do I have to fix the lint? I don't think it's related to this PR.

2020-07-28 17:27 UTC, ysmood commented
@paulirish Do I have to fix the lint? I don't think it's related to this PR.

2021-01-19 19:00 UTC, ysmood commented
Hi @paulirish, what should I do to let this PR be merged?

2021-01-20 03:11 UTC, paulirish requested changes

2021-01-20 03:11 UTC, paulirish commented on readme.md
> +- [Rod](https://github.com/go-rod/rod) - A Devtools driver for web automation and scraping.
```suggestion
```

lets remove this. we don't need it in two places

2021-01-20 03:17 UTC, merged